<?xml version="1.0" ?>

<!DOCTYPE testcases [
  <!ELEMENT testcases (config*, testcase*)>
  <!ELEMENT testcase (config*)>
     <!ATTLIST testcase 
               name CDATA #REQUIRED
               filename CDATA #IMPLIED
               nooutput CDATA #IMPLIED
               class CDATA #IMPLIED
     >
  <!ELEMENT config EMPTY>
     <!ATTLIST config 
            auto_import CDATA #IMPLIED
            clear_encoding_map (Y|N) #IMPLIED
            input_encoding CDATA #IMPLIED
            locale CDATA #IMPLIED
            object_wrapper CDATA #IMPLIED
            output_encoding CDATA #IMPLIED
            output_dir CDATA #IMPLIED
            strict_syntax (Y|N) #IMPLIED
            new_builtin_class_resolver CDATA #IMPLIED
            url_escaping_charset CDATA #IMPLIED
            templatedir CDATA #IMPLIED
            referencedir CDATA #IMPLIED
      >
]>

<testcases>
   <config templatedir="templates"
           referencedir="references"
           input_encoding="UTF-8"
           output_encoding="UTF-8"
   />
   
   <testcase name="arithmetic" filename="arithmetic.html" />
   <testcase name="bean-maps" filename="bean-maps.html"/>
   <testcase name="beans" filename="beans.html">
      <config object_wrapper="freemarker.ext.beans.BeansWrapper"/>
   </testcase>
   <testcase name="boolean" filename="boolean.html" />
   <testcase name="charset-in-header" filename="charsetinheader.html">
      <config clear_encoding_map="Y"/>
      <config input_encoding="ISO-8859-5"/>
   </testcase>
   <testcase name="comment" filename="comment.html" />
   <testcase name="comparisons" filename="comparisons.html" />
   <testcase name="dateformat" filename="dateformat.html" />
   <testcase name="default" filename="default.ftl"/>
   <testcase name="default-xmlns" filename="defaultxmlns1.txt">
      <config object_wrapper="freemarker.ext.beans.BeansWrapper"/>
   </testcase>
   <testcase name="encoding-builtins" filename="encodingbuiltins.txt" />
   <testcase name="escapes" filename="escapes.txt" />
   <testcase name="hashliteral" filename="hashliteral.html" />
   <testcase name="identifier" filename="identifier.html" >
      <config strict_syntax="N" />
   </testcase>
   <testcase name="import" filename="import.txt">
      <config auto_import="import_lib.txt as my"/>
   </testcase>
   <testcase name="include" filename="include.html" />
   <testcase name="interpret" filename="interpret.html"/>
   <testcase name="iterators" filename="listiterators.html"/>
   <testcase name="jsptaglibs" filename="jsptaglibs.txt" 
             class="freemarker.test.templatesuite.servlets.TestJspTaglibs"/>
   <testcase name="lastcharacter" filename="lastcharacter.html"/>
   <testcase name="list" filename="extlist.html" />
   <testcase name="listliteral" filename="listliteral.html" />
   <testcase name="localization" filename="local.html" >
      <config locale="en_AU"/>
   </testcase>
   <testcase name="loopvariable" filename="loopvar.txt" />
   <testcase name="macros" filename="function.html"/>
   <testcase name="macros2" filename="macro.html"/>
   <testcase name="multimodels" filename="models.html"/>
   <testcase name="nested" filename="nested1.txt" />
   <testcase name="newlines1" filename="newlines1.html" />
   <testcase name="newlines2" filename="newlines2.html" />
   <testcase name="noparse" filename="noparse.html" />
   <testcase name="number-format" filename="numberformat.txt" />
   <testcase name="number-literal" filename="numberliteral.html" >
      <config locale="fr_FR"/>
   </testcase>
   <testcase name="numerical-cast" filename="numericalcast.txt" />
   <testcase name="output-encoding1" filename="outputencoding1.txt"/>
   <testcase name="output-encoding2" filename="outputencoding2.txt">
       <config output_encoding="UTF-16"/>
   </testcase>
   <testcase name="output-encoding3" filename="outputencoding3.txt">
       <config output_encoding="ISO-8859-1" url_escaping_charset="UTF-16" />
       
   </testcase>
   <testcase name="precedence" filename="precedence.html"/>
   <testcase name="recover" filename="recover.ftl" />
   <testcase name="root" filename="root.html" />
   <testcase name="sequence-builtins-with-BeansWrapper" filename="sequencebuiltins.txt">
      <config object_wrapper="freemarker.ext.beans.BeansWrapper"/> 
   </testcase>
   <testcase name="sequence-builtins-with-DefaultObjectWrapper" filename="sequencebuiltins.txt">
      <config object_wrapper="freemarker.template.DefaultObjectWrapper"/> 
   </testcase>
   <testcase name="sequence-builtins-with-SimpleObjectWrapper" filename="sequencebuiltins.txt">
      <config object_wrapper="freemarker.template.SimpleObjectWrapper"/> 
   </testcase>
   <testcase name="strictinheader" filename="strictinheader.html">
      <config strict_syntax="N"/>
   </testcase>
   <testcase name="string-builtins1" filename="stringbuiltins.txt" />
   <testcase name="string-builtins2" filename="stringbuiltins2.txt" />
   <testcase name="string-builtins-regexps" />
   <testcase name="stringbimethods" />
   <testcase name="stringliteral" filename="stringliteral.html"/>
   <testcase name="switch-case" filename="switch.html" />
   <testcase name="transforms" filename="transformation.html"/>
   <testcase name="type-builtins" filename="typebuiltins.txt"/>
   <testcase name="var-layers" filename="varlayers.txt"/>
   <testcase name="variables" filename="variables.html"/>
   <testcase name="whitespace-trim" filename="wstrim.txt"/>
   <testcase name="wstrip-in-header" filename="wsstripinheader.txt"/>
   <testcase name="xml-fragment" filename="xmlfragment.txt">
      <config object_wrapper="freemarker.ext.beans.BeansWrapper"/> 
   </testcase>
   <testcase name="xmlns1" filename="xmlns.html">
      <config object_wrapper="freemarker.ext.beans.BeansWrapper"/>
   </testcase>
   <testcase name="xmlns2" filename="xmlns.html">
      <config object_wrapper="freemarker.ext.beans.BeansWrapper"/>
   </testcase>
   <testcase name="xmlns3" filename="xmlns3.html">
      <config object_wrapper="freemarker.ext.beans.BeansWrapper"/>
   </testcase>   
   <testcase name="xmlns4" filename="xmlns4.html">
      <config object_wrapper="freemarker.ext.beans.BeansWrapper"/>
   </testcase>   
   <testcase name="xmlns5" filename="xmlns5.txt">
      <config object_wrapper="freemarker.ext.beans.BeansWrapper"/>
   </testcase>   
   <testcase name="hashconcat" filename="hashconcat.ftl"/>
   <testcase name="new-defaultresolver" />
   <testcase name="new-unrestricted">
      <config new_builtin_class_resolver="unrestricted"/>
   </testcase>   
   <testcase name="new-safer">
      <config new_builtin_class_resolver="safer"/>
   </testcase>   
   <testcase name="new-allowsnothing">
      <config new_builtin_class_resolver="allows_nothing"/>
   </testcase>   
   <testcase name="new-optin">
      <config new_builtin_class_resolver="allowed_classes: freemarker.test.templatesuite.models.NewTestModel, trusted_templates: subdir/new-optin.txt, subdir/subsub/*"/>
   </testcase>   
   <testcase name="specialvars">
      <config locale="en_US"/>
      <config output_encoding="utf-8"/>
      <config url_escaping_charset="iso-8859-1"/>
   </testcase>   
   <testcase name="iso8601" />
   <testcase name="number-to-date" />
   <testcase name="varargs" />
   <testcase name="overloaded-methods-23bc" nooutput="true" />
   <testcase name="classic-compatible">
      <config classic_compatible="true"/>
   </testcase>   
</testcases>
